export const FETCHING_DATA_START = 'FETCHING_DATA_START';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_FAIL = 'FETCHING_DATA_FAIL';

export const FETCHING_DESCRIPTION_START = 'FETCHING_DESCRIPTION_START';
export const FETCHING_DESCRIPTION_SUCCESS = 'FETCHING_DESCRIPTION_SUCCESS';
export const FETCHING_DESCRIPTION_FAIL = 'FETCHING_DESCRIPTION_FAIL';
